/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package former;

import java.awt.Color;
import java.awt.Graphics;
//import java.awt.event.MouseAdapter;
//import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Random;

/**
 *
 * @author okama01
 */
public class FormerJPanel extends javax.swing.JPanel implements Runnable {

    private volatile Thread trad;

    ArrayList<Form> formlista = new ArrayList<>();  // skapa arraylist för att spara informatiobn
     FileManager fmgr = new FileManager();

    private int width, height, radia;
    private int x, y;

    public int numPoints;

    Random rand = new Random();

    /**
     * Creates new form FormerJPanel
     */
    public FormerJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        rbtng1 = new javax.swing.ButtonGroup();
        rensebtn = new javax.swing.JButton();
        startbtn = new javax.swing.JButton();
        triangelrbtn = new javax.swing.JRadioButton();
        cirkelrbtn = new javax.swing.JRadioButton();
        rektangelrbtn = new javax.swing.JRadioButton();
        Savebtn = new javax.swing.JButton();
        hämtabtn = new javax.swing.JButton();

        jButton6.setText("jButton6");

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        rensebtn.setText("Rensa");
        rensebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rensebtnActionPerformed(evt);
            }
        });

        startbtn.setText("Start");
        startbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtnActionPerformed(evt);
            }
        });

        rbtng1.add(triangelrbtn);
        triangelrbtn.setSelected(true);
        triangelrbtn.setText("Triangel");

        rbtng1.add(cirkelrbtn);
        cirkelrbtn.setText("Cirkel");
        cirkelrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cirkelrbtnActionPerformed(evt);
            }
        });

        rbtng1.add(rektangelrbtn);
        rektangelrbtn.setText("Rektangel");

        Savebtn.setText("Spara");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });

        hämtabtn.setText("Hämta");
        hämtabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hämtabtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(triangelrbtn)
                .addGap(39, 39, 39)
                .addComponent(cirkelrbtn)
                .addGap(42, 42, 42)
                .addComponent(rektangelrbtn)
                .addGap(18, 18, 18)
                .addComponent(startbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rensebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Savebtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hämtabtn)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rensebtn)
                    .addComponent(startbtn)
                    .addComponent(triangelrbtn)
                    .addComponent(cirkelrbtn)
                    .addComponent(rektangelrbtn)
                    .addComponent(Savebtn)
                    .addComponent(hämtabtn))
                .addContainerGap(457, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rensebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rensebtnActionPerformed
        formlista.clear();
        repaint();

    }//GEN-LAST:event_rensebtnActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        System.out.println(evt.getX());
        int mouseX = evt.getX();
        int mouseY = evt.getY();
        int b = (int) (Math.random() * 150);
        int h = (int) (Math.random() * 150);
        //int b = (int) (Math.random() * 50) + 85;
        //int h = (int) (Math.random() * 50) + 60;
        if (this.cirkelrbtn.isSelected()) {

            Form t = new Cirkel(mouseX - h / 2, mouseY - h / 2, h, true);

            formlista.add(t);

        } else if (this.rektangelrbtn.isSelected()) {
            Form r = new Rektangel(mouseX - b / 2, mouseY - h / 2, b, h, true);
            formlista.add(r);

        } else {
            Form t = new Triangle(mouseX - b / 2, mouseY + h / 2, b, h, true);

            formlista.add(t);
        }
        repaint();
    }//GEN-LAST:event_formMouseClicked

    private void cirkelrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cirkelrbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cirkelrbtnActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        fmgr.saveToFile(formlista);
    }//GEN-LAST:event_SavebtnActionPerformed

    private void hämtabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hämtabtnActionPerformed
        // TODO add your handling code here:
        formlista = FileManager.readFromFile();

        for (int i = 0; i < formlista.size(); i++) {
            formlista.get(i);
        }
        repaint();

    }//GEN-LAST:event_hämtabtnActionPerformed

    private void startbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtnActionPerformed
        // TODO add your handling code here:

        //     FormerJPanel.getLocation(FormerJPanel.getLocation().x,FormerJPanel.getLocation().y-5 );

    }//GEN-LAST:event_startbtnActionPerformed
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        for (int i = 0; i < formlista.size(); i++) {
            formlista.get(i).Draw(g);
        }

    }

    private Color randomColor() {
        return new Color(rand.nextInt(256), rand.nextInt(256), rand.nextInt(256));

    }

    private int randomPixel() {
        //int pix = (int) (Math.random() * 400);
        int randomNum = (int) (Math.random() * 301); // 0 to 100
        //  return pix;
        return randomNum;
        // int x =(int) radom.math; 
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Savebtn;
    private javax.swing.JRadioButton cirkelrbtn;
    private javax.swing.JButton hämtabtn;
    private javax.swing.JButton jButton6;
    private javax.swing.ButtonGroup rbtng1;
    private javax.swing.JRadioButton rektangelrbtn;
    private javax.swing.JButton rensebtn;
    private javax.swing.JButton startbtn;
    private javax.swing.JRadioButton triangelrbtn;
    // End of variables declaration//GEN-END:variables

    private void start() {
        if (trad == null) {
            trad = new Thread(this);
            trad.start();
            //  this.running = true;
        }
    }

    private void stop() {
        if (trad != null) {
            //    this.running = false;
            trad = null;
        }
    }

    @Override
    public void run() {
        Thread thisThread = Thread.currentThread();
        while (trad == thisThread) {
            try {
                Thread.sleep(30);
            } catch (InterruptedException e) {
            }
            repaint();
        }
    }
}
